### ISSUE TITLE
node Gyp error when using npm ci for kyber repo

### ISSUE THREAD

**Issue by ilanDoron** [frangio/nicer-node-gyp#3]
tried using node-gyp

I run these commands:

git clone git@github.com:KyberNetwork/smart-contracts
cd smart-contracts
npm ci

and get this:
node-gyp-cache: error running node-gyp

**Comment by frangio** [comment]
Thanks for reporting @ilanDoron. I will take a look.

**Comment by frangio** [comment]
I was able to run `npm ci` successfully using Node 10. Can you tell me what version of Node you're using?

**Comment by frangio** [comment]
I was now able to reproduce the problem using Node 12. It seems to be an incompatibility with Node, probably caused by the old versions of dependencies, such as `web3@^0.20`.

Right below the message `error running node-gyp` you should see a message that says `logs saved at <path>`. (I should make this message more prominent...) If you open the file at `<path>` you will see the node-gyp logs with the compilation errors.

**Comment by ilanDoron** [comment]
Thanks for taking a look at this

what do u suggest?
that I use node 10?

I would very much like to update packages. but most of the times its not in
my control
other packages include non updated packages.

please advice.
thanks

**Comment by frangio** [comment]
Yes, you should use Node 10. Unfortunately most of the Ethereum ecosystem does not work on Node 12.
