### ISSUE TITLE
How do I know that it is working?

### ISSUE THREAD

**Issue by bartenew** [frangio/nicer-node-gyp#5]
I installed the package as dev and added local .npmrc using `echo node_gyp = node-gyp-cache >> .npmrc`

Yet I don't see any changes or cache folder created.

**Comment by frangio** [comment]
When you install a package that uses node-gyp to compile native extensions you should see on your console a message that says either of:

- `✔ node-gyp-cache: rebuilt and cached`
- `✔ node-gyp-cache: restored build from cache`

And you should not see any compiler output.

If you're building for the Ethereum ecosystem this won't happen as much because native extensions are used a lot less now.

**Comment by frangio** [comment]
You can try this with the package `keccak@2.0.0`. Newer versions of this package will not show the message because they no longer rely on native extensions.
